// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgMdcYzA21q_ZnBmUmF-j0_Em03EX343Y',
    appId: '1:926446362704:web:59da0949e4bca8c7237155',
    messagingSenderId: '926446362704',
    projectId: 'contactapp-52395',
    authDomain: 'contactapp-52395.firebaseapp.com',
    storageBucket: 'contactapp-52395.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4Lg-wb71j29zHCorFsSAk2P6Xya_p99A',
    appId: '1:926446362704:android:27916bfb40e877ae237155',
    messagingSenderId: '926446362704',
    projectId: 'contactapp-52395',
    storageBucket: 'contactapp-52395.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRBGtsnRUmJH7q9R-rVAhP3ibOMiwch9E',
    appId: '1:926446362704:ios:f8901c662157e4ef237155',
    messagingSenderId: '926446362704',
    projectId: 'contactapp-52395',
    storageBucket: 'contactapp-52395.appspot.com',
    iosBundleId: 'com.example.audioBookApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRBGtsnRUmJH7q9R-rVAhP3ibOMiwch9E',
    appId: '1:926446362704:ios:46b2acb90d84a7c4237155',
    messagingSenderId: '926446362704',
    projectId: 'contactapp-52395',
    storageBucket: 'contactapp-52395.appspot.com',
    iosBundleId: 'com.example.audioBookApp.RunnerTests',
  );
}
